version: "3.3"

networks:

   testing:
      name: custom_network
      ipam: # ipam = ap address management 
         driver: default 
         config:
            - subnet: 192.168.92.0/24
   

services:

  backend:
     image: 0abraham0/backend_image:latest
     container_name: backend
     build: ./web-app/backend
     ports:
       - 5001:5001
     networks:
       - testing
  frontend:
     image: 0abraham0/frontend_image:latest
     container_name: frontend
     build: ./web-app/frontend
     ports:
       - 3001:3000
     networks:
       - testing
     depends_on:
       - backend
     