name: Pull Request Test

on:
  pull_request:
    branches:
      - main
  #   paths:
  #     - web-app/**
  # workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web-app/

    strategy:
      matrix:
        python-version: [3.10]

    env:
      MODE: "dev"


    steps:
      - uses: actions/checkout@v3

      # Setup Nodejs
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          # cache: 'npm'
          # cache-dependency-path: web-app/yarn.lock
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/

      - name: Test server.py
        run: python3 ./server.py

      # # Install Yarn
      # - name: Install Yarn
      #   run: npm install --global yarn

      # # Install libraries
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      # # Run linting
      # - name: Run linting
      #   run: yarn lint

      # # Compile the code
      # - name: Build project
      #   run: yarn build

      # # Run tests
      # - name: Run tests
      #   run: yarn test